---
title: "HW3"
author: "Devan Becker"
date: "2/7/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(tidyverse)
```

```{r}
fisheries <- readr::read_csv(file = "FAO_1950to2012_111914.csv")
```

```{r}
names(fisheries) = make.names(names(fisheries), unique = T)
names(fisheries)
```
```{r}
fisheries
```

```{r}
fisheries <- fisheries %>% 
  rename(country = Country..Country.,
         commname = Species..ASFIS.species.,
         sciname = Species..ASFIS.species._2,
         spcode = Species..ASFIS.species._1,
         spgroup = Species..ISSCAAP.group., 
         spgroupname = Species..ISSCAAP.group._1, 
         region = Fishing.area..FAO.major.fishing.area., 
         unit = Measure..Measure.)
fisheries
```
```{r}
fisheries_tidy <- fisheries %>% 
  gather(num_range("X",1950:2012), key="year", value="catch")
```

```{r}
glimpse(fisheries_tidy)
```

```{r}
fisheries_tidy <- fisheries_tidy %>% 
  mutate(year = as.numeric(str_replace(year, "X", "")), 
         catch = as.numeric(str_replace(catch, c("F", "...", "-"), replacement = "")))
```

```{r}
fisheries_tidy
```

```{r}
fisheries_tidy %>% 
  select(country, spgroupname, year, catch) %>% 
  filter(year==2012, spgroupname=="Squids, cuttlefishes, octopuses") %>% 
  arrange(desc(catch))
```
```{r}
cuttlefish <- 
  fisheries_tidy %>% 
  select(country, commname, sciname, year, catch) %>% 
  filter(year==2012, commname=="Common cuttlefish") %>%
  arrange(desc(catch))
cuttlefish
```


